### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by colorvamp** [bobby1030/crx-to-xpi#1]
```
nodejs /usr/local/lib/node_modules/crx-to-xpi/src/crx-to-xpi.js ext.crx 
/usr/local/lib/node_modules/crx-to-xpi/src/crx-to-xpi.js:11
var log = (type = 'status', content) => {
                ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

nodejs --version
v4.2.6

**Comment by colorvamp** [comment]
With v6.11.2 it works perfect, sorry for the noise
