### ISSUE TITLE
Uncaught (in promise) Error: Unexpected crx format version number

### ISSUE THREAD

**Issue by bdavisonhelo** [bobby1030/crx-to-xpi#3]
$ crx-to-xpi /Users/myusername/Downloads/extension_1_4_137_0.crx 
Error: Failed to unpack CRX file
Uncaught (in promise) Error: Unexpected crx format version number.
    at crxToZip (/usr/local/lib/node_modules/crx-to-xpi/node_modules/unzip-crx/dist/index.js:37:15)
    at /usr/local/lib/node_modules/crx-to-xpi/node_modules/unzip-crx/dist/index.js:57:32
    at callHanler (/usr/local/lib/node_modules/crx-to-xpi/node_modules/yaku/lib/yaku.js:719:16)
    at tryCatcher (/usr/local/lib/node_modules/crx-to-xpi/node_modules/yaku/lib/yaku.js:436:32)
    at /usr/local/lib/node_modules/crx-to-xpi/node_modules/yaku/lib/yaku.js:575:38
    at flush (/usr/local/lib/node_modules/crx-to-xpi/node_modules/yaku/lib/yaku.js:478:17)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

Any ideas?

**Comment by RikisuT** [comment]
Same here...

**Comment by ghost** [comment]
Same problem still

**Comment by skrlst** [comment]
Same...

**Comment by DH-LStudios** [comment]
Same here

**Comment by n0-n4-m3** [comment]
same xD

**Comment by kevinmost** [comment]
Looks like this is due to crx3 not being supported in the `unzip-crx` project upstream. 

Someone has forked that project and added crx3 support. See: https://github.com/peerigon/unzip-crx/issues/12

Changing the `unzip-crx` usages in `package.json` and `src/crx-to-xpi.js` to `unzip-crx-3` should be enough to fix this.
